# Generated by Django 5.2.17 on 2026-10-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Sistema / Equipamento')),
                ('system_type', models.CharField(choices=[('SDAI', 'Sistema de Detecção e Alarme de Incêndio'), ('BOMBAS', 'Casa de Bombas / Motobombas'), ('SPRINKLERS', 'Rede de Chuveiros Automáticos (Sprinklers)'), ('ILUMINACAO', 'Iluminação de Emergência'), ('EXTINTORES', 'Extintores de Incêndio'), ('OUTRO', 'Outro Sistema')], default='SDAI', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo / Marca')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização na Planta')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Série')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações Técnicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.client', verbose_name='Cliente')),
            ],
        ),
    ]
