# Generated by Django 5.2.17 on 2026-10-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Modelo')),
                ('equipment_type', models.CharField(choices=[('SDAI', 'Sistema de Detecção e Alarme de Incêndio'), ('BOMBAS', 'Casa de Bombas / Motobombas'), ('SPRINKLERS', 'Rede de Chuveiros Automáticos (Sprinklers)'), ('ILUMINACAO', 'Iluminação de Emergência'), ('EXTINTORES', 'Extintores de Incêndio'), ('OUTRO', 'Outro Sistema')], default='SDAI', max_length=50, verbose_name='Tipo de Equipamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inspectioncategory',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='inspectionitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='inspectioncategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='title',
        ),
        migrations.AddField(
            model_name='inspectioncategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='inspectioncategory',
            name='title',
            field=models.CharField(default='GERAL', max_length=255, verbose_name='Título da Categoria / Bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='label',
            field=models.CharField(default='Item Geral', max_length=255, verbose_name='Pergunta / Item de Inspeção'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='response_type',
            field=models.CharField(choices=[('BOOLEAN', 'Sim / Não / N/A (Conforme / Não Conforme)'), ('NUMBER', 'Número / Medição (Volts, PSI, Horímetro)'), ('TEXT', 'Texto Livre / Observação')], default='BOOLEAN', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectioncategory',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.inspectiontemplate'),
            preserve_default=False,
        ),
    ]
