# Generated by Django 5.2.17 on 2026-10-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inspectiontemplate_alter_inspectioncategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='technicians_count',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='title',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in Real'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out Real'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='complementary_services',
            field=models.TextField(blank=True, null=True, verbose_name='Serviços Complementares'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='conclusions',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusões / Observações Técnicas'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='execution_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Previsto'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='execution_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início Previsto'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='os_number',
            field=models.CharField(default='OS-000', max_length=50, unique=True, verbose_name='Número da O.S.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='scope',
            field=models.TextField(blank=True, null=True, verbose_name='Escopo do Trabalho'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='service_orders', to='api.teammember'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aguardando Despacho'), ('em_campo', 'Em Campo'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceOrderEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_inspections', to='api.equipment')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_equipments', to='api.serviceorder')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inspectiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SIM', 'Sim / Conforme'), ('NAO', 'Não / Não Conforme'), ('NA', 'N/A (Não Aplicável)')], default='SIM', max_length=10)),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Medido / Observação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspectionitem')),
                ('order_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.serviceorderequipment')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nome do Responsável do Cliente')),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='signatures/client/')),
                ('technician_name', models.CharField(max_length=255, verbose_name='Nome do Técnico')),
                ('technician_signature', models.ImageField(blank=True, null=True, upload_to='signatures/tech/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='api.serviceorder')),
            ],
        ),
    ]
