# Generated by Django 6.1.1 on 2026-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inspectionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Administrador', 'Administrador'), ('Técnico de campo', 'Técnico de campo'), ('Supervisor', 'Supervisor')], default='Técnico de campo', max_length=50)),
                ('status', models.CharField(default='online', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='image',
            field=models.ImageField(upload_to='inspection_photos/'),
        ),
    ]
