# Generated by Django 6.1.1 on 2026-09-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teammember_alter_inspectionphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('plan', models.CharField(default='Profissional', max_length=100)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=1890.0, max_digits=10)),
                ('users_count', models.IntegerField(default=1, verbose_name='Número de Usuários')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('trial', 'Trial'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
